spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:  password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

zuul:
  routes:
    serviceSimple:
      path: /greeting/simple
      url: forward:/
    serviceAdvanced:
      path: /greeting/advanced
      url: forward:/
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      serviceSimple:
      - limit: 5
        refresh-interval: 60
        type:
        - origin
      serviceAdvanced:
      - limit: 1
        refresh-interval: 2
        type:
        - origin
  strip-prefix: true